### ISSUE TITLE
나는 아직 배가고프다

### ISSUE THREAD

**Issue by hellojdh** [huisam/Chatting_Talk#1]
> e362a6e15f3f7ab6c0d6c7bc92fd793921384069
@huisam 정리한 코드 잘 봤습니다~!
Server 단에서 Socket도 finally를 통해 close 해주는 것은 어떤가요!

**Comment by huisam** [comment]
앗, 예리한 지적 감사합니다~!
서버쪽을 깜빡하고 닫는 것을 못했다니..!
피드백 받고 수정했습니다
